import { ComplicatedStats } from "./types";

export const complicatedStats: ComplicatedStats = {
    secretary: {
      tier1Stats: [],
      tier2Stats: ["userPC", "management"],
      tier3Stats: ["coffeeBrewing"],
      name: "Секретарь",
      description: "Мастерстро ведения бухгалтерии и выполнения поручений",
      lessonText: [
        "Не секретарь",
        "Посредственный секретарь",
        "Слабенький секретарь",
        "Секретарь",
        "Хороший секретарь",
        "Секретарь с Уолл-Стрит",
      ],
    },
    showman: {
      tier1Stats: [],
      tier2Stats: [],
      tier3Stats: ["singing", "dance"],
      name: "Шоумен",
      description: "Умение выступать, петь и танцевать на сцене",
      lessonText: [
        "Не музыкант",
        "Начинающий музыкант",
        "музыкант-стажёр",
        "Музыкант",
        "Музыкант",
        "Идол",
      ],
    },
    factoryman: {
      tier1Stats: ["technicalProcess", "userPC", "firstAid"],
      tier2Stats: [],
      tier3Stats: ["factoryMachines", "preventionOfAccidents"],
      name: "Заводчанин",
      description: "Умение работать на заводе.",
      lessonText: [
        "Не заводчанин",
        "Подпивас",
        "Мужик",
        "Работяга",
        "Батя",
        "Красава",
      ],
    },
    constructor: {
      tier1Stats: ["firstAid"],
      tier2Stats: ["heavyMachinery"],
      tier3Stats: ["construction", "preventionOfAccidents"],
      name: "Cтроитель",
      description:
        "Умение строить здания и прочие интересные штуки, в которых могут жить и работать люди.",
      lessonText: [
        "Не строитель",
        "Принеси-подай",
        "чернорабочий",
        "Строитель",
        "Строитель",
        "Мишка-строитель",
      ],
    },
    boss: {
      tier1Stats: ["heavyMachinery"],
      tier2Stats: ["construction"],
      tier3Stats: [
        "technicalProcess",
        "factoryMachines",
        "preventionOfAccidents",
        "userPC",
      ],
      name: "Босс завода",
      description: "Высший навык любого заводчанина. Завод - это ты.",
      lessonText: [
        "Не босс",
        "Боссичонок",
        "Боссичек",
        "Боссик",
        "Бочонок",
        "Босс",
      ],
    },
    doctor: {
      tier1Stats: [],
      tier2Stats: ["firstAid"],
      tier3Stats: ["doctoring", "surgery"],
      name: "Доктор",
      description: "Врач.",
      lessonText: [
        "Не доктор",
        "Санитар",
        "Интерн",
        "Доктор",
        "Главврач",
        "Рука Бога",
      ],
    },
    
    paragon: {
      tier1Stats: ["userPC", "technicalProcess"],
      tier2Stats: [ "construction"],
      tier3Stats: [
        "surgery",
        "factoryMachines",
        "heavyMachinery"
      ],
      name: "Босс-вертолёт",
      description: "Парагон",
      lessonText: [
        "Не босс",
        "Не босс",
        "Не босс",
        "Не босс",
        "Почти босс",
        "БОСС",
      ],
    },
  };