import { SlaveImg } from "./types";

export const slaveImg: SlaveImg = {
    avatar: "avatar.png",
    normal: "normal.png",
    reject: "_rejection.png",
    singing: "_singing.png",
    dance: "_dance.png",
    systemAdministration: "_pc.png",
    programming: "_pc.png",
    coffeeBrewing: "_coffee.png",
    doctoring: "_doctor.png",
    firstAid: "_doctor.png",
    surgery: "_surgery.png",
    driving: "driving.png",
    userPC: "_pc.png",
    management: "_pc.png",
    preventionOfAccidents: "preventionOfAccidents.png",
    construction: "construction.png",
    heavyMachinery: "heavyMachinery.png",
    factoryMachines: "factoryMachines.png",
    technicalProcess: "study.png",
    happy1: "happy1.png",
    happy2: "happy2.png",
    happy3: "happy3.png",
    sad1: "sad1.png",
    sad2: "sad2.png",
    sad3: "sad3.png",
    laborerWork: "sad3.png",
    programmerWork: "_pc.png",
    secretaryWork: "_coffee.png",
    accountantWork: "_coffee.png",
    plantManagerWork: "_singing.png",
    driverWork: "driving.png",
    doctorWork: "_surgery.png",
    constructorWork: "construction.png",
    factoryWorkerWork: "factoryMachines.png",
    sysAdminWork: "_pc.png",
  };